<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Chanders-MacBook-Air.local" name="com.crm.testcases.HomePageTest" tests="6" failures="0" timestamp="20 Nov 2018 06:09:26 GMT" time="0.009" errors="1">
  <testcase name="dealspageTest" time="0.000" classname="com.crm.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- dealspageTest -->
  <testcase name="setUp" time="0.009" classname="com.crm.testcases.HomePageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.crm.base.TestBase.intialization(TestBase.java:41)
	at com.crm.testcases.HomePageTest.setUp(HomePageTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="taskspageTest" time="0.000" classname="com.crm.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- taskspageTest -->
  <testcase name="contactspageTest" time="0.000" classname="com.crm.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- contactspageTest -->
  <testcase name="usernamedisplayTest" time="0.000" classname="com.crm.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- usernamedisplayTest -->
  <testcase name="verifyHomePagetitleTest" time="0.000" classname="com.crm.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyHomePagetitleTest -->
</testsuite> <!-- com.crm.testcases.HomePageTest -->
